

package io.github.nomisrev.typedapi.compiler.plugin.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link io.github.nomisrev.typedapi.compiler.plugin.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler-plugin/testData/box")
@TestDataPath("$PROJECT_ROOT")
public class JvmBoxTestGenerated extends AbstractJvmBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler-plugin/testData/box"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
  }

  @Test
  @TestMetadata("hello.kt")
  public void testHello() {
    runTest("compiler-plugin/testData/box/hello.kt");
  }

  @Test
  @TestMetadata("newConstructor.kt")
  public void testNewConstructor() {
    runTest("compiler-plugin/testData/box/newConstructor.kt");
  }

  @Test
  @TestMetadata("pathWithParams.kt")
  public void testPathWithParams() {
    runTest("compiler-plugin/testData/box/pathWithParams.kt");
  }

  @Test
  @TestMetadata("query.kt")
  public void testQuery() {
    runTest("compiler-plugin/testData/box/query.kt");
  }
}
